name: Custom Android Build (channel=prod)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: custom-android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with:
      upload-artifact: true
      channel: prod